### ISSUE TITLE
DefaultItems does not work

### ISSUE THREAD

**Issue by cambronjay** [jasonmamy/cordova-wheel-selector-plugin#7] opened 2017-06-07 14:00 UTC
How do you really set defaultItems? I have set up my data structure and when I set the defaultItems as the description value it does not work. It gives the error of invalid selector.

**Comment by jasonmamy** [comment] 2017-06-07 17:00
Can you paste your code in so I can see it?  Are you on ios or android?

**Comment by jasonmamy** [comment] 2017-06-08 17:40
I just tried the example app, and at least on android, the default items were set correctly, check out the example:


https://github.com/jasonmamy/cordova-wheel-selector-plugin/blob/master/examples/testapp/www/js/app.js#L257

**Comment by Nehluxhes** [comment] 2017-06-12 09:21
I don't know about your example but I can confirm it didn't work for me either with the form described in the options description, I had to use the form { "description": "value" } .

```
let values = [];
      for (let i = 1; i <= 80; ++i) {
        values.push({ description: "" + i });
      }
this._wheel.show({
          title: "",
          items: [values, values],
          //defaultItems: ["5", "8"], // Doesn't work
          defaultItems: [{"description": "5"}, { "description": "8"}], // Works
          positiveButtonText: "Done",
          negativeButtonText: "Cancel"
        }).then((result) => {
          console.log("result is ", result);
        }).catch((err) => { console.log(err); });
```
I am using Ionic 2 with Android.

**Comment by cambronjay** [comment] 2017-06-12 12:36
I am using the example code in iOS and it gives an error when I try to place anything in defaultItems. I have tried Nehluxhes's format and your example app format.

**Comment by jasonmamy** [comment] 2017-06-16 18:15
Yea, I see the issue, looks like Nehluxhes has it right:

`defaultItems: [{"description": "5"}, { "description": "8"}]`

Which can be shorthanded to:

`defaultItems: [values[4], values[5]]`

I can update the docs to match this, as the intention was to not have to duplicate any json, but rather reference the original data set.

For iOS I'll have to ask @xatshepsut:

Can you look at iOS to see if the defaultItems matches up to the iOS native code?

Thanks

**Comment by xatshepsut** [comment] 2017-06-18 20:29
I haven't checked the documentation. The defaultItems on iOS was expected to be used as

```
defaultItems: {
    '0': 'value',
    '1': 'value'
}
```

where the number indicates index of data array default is intended for. This allows to set defaults only for data that needs default value, unlike array notations where we need to specify a value for each column.

**Comment by cambronjay** [comment] 2017-06-20 13:17
Have you tested this on iOS? @xatshepsut

**Comment by xatshepsut** [comment] 2017-06-20 18:27
@cambronjay yes, I've pushed that change from my fork which was used in production code.

We haven't properly synced my solution on iOS and @jasonmamy's on Android though, hence the inconsistency in documentation (documentation applies to Android feature).

**Comment by cambronjay** [comment] 2017-06-21 17:17
So has this change to iOS been pushed to the main branch? Can you update the docs to show exactly how it is done? @jasonmamy @xatshepsut

**Comment by xatshepsut** [comment] 2017-06-22 05:06
It's not just a change pushed on existing feature, it's the actual default items feature for iOS. Where else it should be merged?

My pull request got merged without syncing with Android version. Since there can't be different documentation on same feature for each OS, either Android or iOS solution should be updated. I suggest keeping iOS version as it's more flexible.

**Comment by xatshepsut** [comment] 2017-06-22 05:16
@cambronjay If you're project is using iOS only, you can use the example I've posted above. If it wasn't clear, here's a full example:

```
var config = {
    items: [
        [data.numbers],
        [data.fruit]
    ],
    defaultItems: {
        '1': 'apple'
    }
};
```
'1' indicates index of array, 'apple' is the default value. By default, first value from array is selected when provided value is not found (eg no 'apple' in items[1]) or no default is provided (eg no default for data.numbers).

**Comment by jasonmamy** [comment] 2017-06-22 05:57
I'll fix android to be the same as iOS in the next day or so, and update
the documentation as well, sorry for the confusion.

**Comment by xatshepsut** [comment] 2017-06-22 14:46
Thanks!
I should've checked Android feature and documentation first, sorry about that.

**Comment by jasonmamy** [comment] 2017-06-23 17:41
I fixed android to be the same as iOS, it works on ionic1 and ionic2 (latest version is 1.0.9). 

Updated docs:

https://github.com/jasonmamy/cordova-wheel-selector-plugin#default-items


For ionic2 (until they accept and push into the master), you can get the code here (the interface is slightly different than ionic1):

https://github.com/jasonmamy/ionic-native.git

just do:

```
npm install
npm run build
```

the plugin will be in the `./dist` dir, copy to your local node_modules/@ionic-native dir.

**Comment by KevRyan2** [comment] 2017-12-29 03:44
Currently working on this for angular 2, ionic 2, ios and having trouble with the default values.  It complains about a string being set for the index(as the new documentation looks to ask for):  http://prntscr.com/htn7ek .  And when a number is set for the index: http://prntscr.com/htn9i3 , it just chooses the 0 index.  This is the data set I'm trying to set the default value for: http://prntscr.com/htn9ok

**Comment by conormag** [comment] 2018-04-03 15:28
for default items the docs say:

```var config = {
    title: "Select something",
    items:[
        data.numbers,
        data.fruits
    ],
    defaultItems: {"0":"2", "1":"Pear"} //{index:value, index:value ...}
};
```

but the code says:
```
    if (options.defaultItems != null && options.defaultItems.length > 0) {
      for (i in options.defaultItems) {
        defaultItemsList[options.defaultItems[i].index] = options.defaultItems[i].value;
      }
    }
```

so given that, what works for me on Android & IOS is:
```
defaultItems: [{index:"0", value:"2"}, {index:"1", value:"Pear"}]
```

**Comment by jasonmamy** [comment] 2018-04-13 16:49
Updated the docs to reflect what worked for you (I think it used to work
the other way but it was changed).

Thanks

**Comment by conormag** [comment] 2018-04-19 13:47
Just to clarify, what works is an an array of objects with keys called "index" and "value" and their respective values, which is different from how you updated the documentation.
working: `defaultItems: [{index:"0", value:"2"}, {index:"1", value:"Pear"}]`
not working: `defaultItems: [{"0":"2", "1":"Pear"}]`

**Comment by jasonmamy** [comment] 2018-04-24 18:02
Got it, my bad, I think the not-working example was from a while back when
it used to work in that manner.

**Comment by h3nr1ke** [comment] 2018-09-17 12:40
I tried the following config

```json
{
	"title": "Selecione a data",
	"items": [
		[
			[{
				"value": "1"
			}, {
				"value": "2"
			}, {
				"value": "3"
			}, {
				"value": "4"
			}, {
				"value": "5"
			}, {
				"value": "6"
			}, {
				"value": "7"
			}, {
				"value": "8"
			}, {
				"value": "9"
			}, {
				"value": "10"
			}, {
				"value": "11"
			}, {
				"value": "12"
			}, {
				"value": "13"
			}, {
				"value": "14"
			}, {
				"value": "15"
			}, {
				"value": "16"
			}, {
				"value": "17"
			}, {
				"value": "18"
			}, {
				"value": "19"
			}, {
				"value": "20"
			}, {
				"value": "21"
			}, {
				"value": "22"
			}, {
				"value": "23"
			}, {
				"value": "24"
			}, {
				"value": "25"
			}, {
				"value": "26"
			}, {
				"value": "27"
			}, {
				"value": "28"
			}, {
				"value": "29"
			}, {
				"value": "30"
			}, {
				"value": "31"
			}]
		],
		[
			[{
				"value": "Janeiro"
			}, {
				"value": "Fevereiro"
			}, {
				"value": "Março"
			}, {
				"value": "Abril"
			}, {
				"value": "Maio"
			}, {
				"value": "Junho"
			}, {
				"value": "Julho"
			}, {
				"value": "Agosto"
			}, {
				"value": "Setembro"
			}, {
				"value": "Outubro"
			}, {
				"value": "Novembro"
			}, {
				"value": "Dezembro"
			}]
		],
		[
			[{
				"value": "2018"
			}, {
				"value": "2017"
			}, {
				"value": "2016"
			}, {
				"value": "2015"
			}, {
				"value": "2014"
			}, {
				"value": "2013"
			}, {
				"value": "2012"
			}, {
				"value": "2011"
			}]
		]
	],
	"wrapWheelText": true,
	"positiveButtonText": "OK",
	"negativeButtonText": "Cancelar",
	"displayKey": "value",
	"defaultItems": [{
		"index": "0",
		"value": "31"
	}, {
		"index": "1",
		"value": "Dezembro"
	}, {
		"index": "2",
		"value": "1918"
	}]
}
```
the data selection is working ok, but the default values are not.

tried also
```javascript
"defaultItems": [{
		"0" : "31"
	}, {
		"1" : "Dezembro"
	}, {
		"2" : "2017"
	}
]
```
but no success as well... =(

just make sure, is the index property inside the defautlItems relative to the position of the items inside the wheel or relative to the array of options?

Thanks for the help...

**Comment by h3nr1ke** [comment] 2018-09-17 13:45
So, after some debug, the correct way to set the defaultItems ( at least when using android) is 

```javascript
"defaultItems": {
  "0" : "31",
  "1" : "Dezembro",
  "2" : "2017"
}
```

so, it should not be a json Array, but a json Object directly, since the plugin's code uses

```java
tmpDefaultItemsMightNotBeSet = options.getJSONObject(DEFAULT_SELECTED_ITEMS_KEY);
```

inside SelectorCordovaPlugin.java on line 75.

hope it help someone

**Comment by h3nr1ke** [comment] 2018-09-17 14:00
Just tested the above solution on iOS and it also worked =), now we just need  to update the documentation.

**Comment by h3nr1ke** [comment] 2018-09-17 14:17
I tried to commit send a pull request without success, how can I be a contributor @jasonmamy ?

**Comment by jasonmamy** [comment] 2018-09-20 17:39
I think you just submit a pull request through github (might have to create
a fork first), then I can merge it:

https://help.github.com/articles/creating-a-pull-request/

A few folks have already done this so I know it's possible.

**Comment by JacquesSchalkwyk** [comment] 2018-11-06 06:01
Hi Jason.  I cannot get the defaultItems to work.  could you please have a look and show me where I am going wrong.  Thank you for your assistance. 

import { Component, OnInit } from '@angular/core';
import { ModalController, NavParams } from '@ionic/angular';
import { FormBuilder, FormGroup, FormArray } from '@angular/forms';
import { WheelSelector } from '@ionic-native/wheel-selector/ngx';
import { DataService } from '../services/data.service';

@Component({
  selector: 'app-addload',
  templateUrl: './addload.page.html',
  styleUrls: ['./addload.page.scss'],
})

export class AddloadPage implements OnInit {

  val;
  productForm: FormGroup;
  selectedProduct;
  products: any;
  productLengths: any;
  productIndex: any;

  constructor(
    public modalController: ModalController,
    public navParams: NavParams,
    private selector: WheelSelector,
    private ds: DataService
  ) {

    this.ds.currentProducts.subscribe(Response => {
      this.products = Response;
      console.log(this.products);
    });

    this.ds.currentProductLength.subscribe(Response => {
      this.productLengths = Response;
      this.productLengths = JSON.parse(JSON.stringify(this.productLengths).split('"length":').join('"description":'));
      console.log(this.productLengths);
    });

  }

  ngOnInit() {
    this.val = this.navParams.get('data');
  }

  dismiss() {
    this.modalController.dismiss();
  }

  // basic number selection, index is always returned in the result
  selectProduct() {
    this.selector.show({
      title: 'Select product',
      items: [
        this.products, this.productLengths
      ],
      theme: 'dark',
      wrapWheelText: true,
      defaultItems: [
        { index: 0, value: this.products[this.productIndex].description }
      ]

    }).then(
      result => {
        console.log(result);
        console.log(result[0].description + ' at index: ' + result[0].index);
        this.productIndex = result[0].index;
        console.log(this.productIndex);
        this.selectedProduct = result[0].description /*+ ' - ' + result[1].description + 'm'*/;
      },
      err => console.log('Error: ', err)
    );
  }





}

**Comment by jasonmamy** [comment] 2018-11-06 19:49
I just tested it out, and default items works (see code below).  I added in
an index to 'remember' which item was selected (selectedIndex), so on
subsequent calls the selector will show the last item selected as the
default.  Try the code below in a different test page to verify it works
for you. Then - my guess is that the asynchronous call to get the products
in:


this.ds.currentProducts.subscribe(Response => {
this.products = Response;
console.log(this.products);
});

is not getting resolved before you use it in the selector (I've struggled
with things like that before), one fix is to do this:


selectProduct() {
this.ds.currentProducts.subscribe(Response => {
this.products = Response;
this.selector.show({
//..put in your selector code here, that way guaranteed this.products is
'populated'
})
});
}

Example code with hard-coded product data so you can verify that it works
(run on device)

in UI/HTML:

<button ion-button round outline (click)="selectProduct()">Select Product
</button>

<p>Selected: {{selected}}</p>
<p>Selected Index: {{selectedIndex}}</p>


in .ts file:

export class HomePage {
selected: string;
selectedIndex: number = 0;
jsonData = {
products: [
{ description: "Product 0" },
{ description: "Product 1" },
{ description: "Product 2" },
{ description: "Product 3" },
{ description: "Product 4" },
{ description: "Product 5" }
]
}
constructor(public navCtrl: NavController, public selector: WheelSelector) {
}
selectProduct() {
this.selector.show({
title: "Choose a product",
items: [
this.jsonData.products
],
defaultItems: [
{ index: 0, value: this.jsonData.products[this.selectedIndex].description }
]
}).then(
result => {
this.selected = this.jsonData.products[result[0].index].description;
this.selectedIndex = result[0].index;
},
err => console.log('Error occurred while getting result: ' +
JSON.stringify(err))
);
}
}


Lemme know if this works

**Closed as completed** 2018-12-12 18:47 UTC

**Comment by beard7** [comment] 2019-04-02 12:35
Any chance of getting a definitive answer on this, as none of the examples above seem to work.

My data is defined as follows:
````
var durationData = {
    hours: [
        { value: '0' },
        { value: '1' },
        { value: '2' },
        { value: '3' },
        { value: '4' },
        { value: '5' },
        { value: '6' },
        { value: '7' },
        { value: '8' }
    ],

    minutes: [
        { value: '0' },
        { value: '10' },
        { value: '20' },
        { value: '30' },
        { value: '40' },
        { value: '50' },
    ]
};
````

And the plugin options contains:
 ````
{
    items: [
        [ durationData.hours ],
        [ durationData.minutes ]
    ],
    defaultItems: [
        { index: 0, value: '1' },
        { index: 1, value: '30' }
    ],
    displayKey: 'value'
}
````

The selector works fine, but I simply can't get the default items to work. This is on Android platform 7.1.4.

Thanks

**Comment by jasonmamy** [comment] 2019-04-03 17:20
Check out the docs at:

https://github.com/jasonmamy/cordova-wheel-selector-plugin#default-items

Looks like you might need []'s around your number:

{ index: 0, value: [1] }

See if that works.

**Comment by beard7** [comment] 2019-04-04 07:39
Finally found out the right way to do it (at least on my platform):
`defaultItems: { "0": "2", "1": "30" }`
No need to provide an array, just a JSON object. I'd tried that before, but only with a single default item. It looks like you must provide defaults for all options if you're going to use them.

**Comment by jasonmamy** [comment] 2019-04-05 17:22
Thanks, I updated the docs to mention this, hope it saves other folks the
hassle.

**Comment by ajuanjojjj** [comment] 2019-09-12 12:03
Just wanted to point out that docs arent yet updated, just lost quite some time trying every solution in the thread, beard7's solution worked for me on Apache Cordova, android build 

> Finally found out the right way to do it (at least on my platform):
> `defaultItems: { "0": "2", "1": "30" }`
> No need to provide an array, just a JSON object. I'd tried that before, but only with a single default item. It looks like you must provide defaults for all options if you're going to use them.

**Comment by mirko77** [comment] 2022-07-05 10:52
Still, in 2022, docs are not updated. 
At least on Android, @h3nr1ke is the solution that works.

```

defaultItems: {
0: data.numbers[2].description,
1: data.fruits[2].description
}

```

**Comment by jasonmamy** [comment] 2022-07-05 17:29
Mirko77 - what should I change in the docs?

**Comment by mirko77** [comment] 2022-07-05 17:58
@jasonmamy the `defaultItems` example, from

```

var config = {
    title: "Select something",
    items:[
        [data.numbers],
        [data.fruits]
    ],
    defaultItems: [
        //the number '2'
        {index:0, value: data.numbers[2]},

        //the value 'Pear'
        {index:1, value: data.fruits[2]}
    ]
};

```

to

```

var config = {
    title: "Select something",
    items:[
        [data.numbers],
        [data.fruits]
    ],
    defaultItems: {
        //the number '2'
        0 : data.numbers[2],

        //the value 'Pear'
        1 : data.fruits[2]
    }
};

```

at least on Android, I have not tested iOS yet

**Comment by jasonmamy** [comment] 2022-07-05 18:13
Ok, updated the docs, thanks for finding the issue!
